---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.25.0
    hooks:
      - id: yamllint
        name: Run yamllint
        description: Lint yaml files
  - repo: https://github.com/ansible/ansible-lint
    rev: v4.3.7
    hooks:
      - id: ansible-lint
        name: Run ansible-lint
        description: Lint ansible files
        exclude: ansible/group_vars|ansible/vault_vars
  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]
