---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false

  vars_files:
    - ../../defaults/main.yaml
    - ../../vars/main.yaml

  tasks:
    - name: Check {{ bin_name }} version.
      command: "{{ app_install_link }} {{ verify_arg }}"
      changed_when: false
      register: app_verify_version

    - name: Verify '{{ bin_name }} version is {{ app_ver }}.
      assert:
        that:
          - app_ver in app_verify_version.stdout
